public class Constants {

    //Email Templates
    public static string EMAIL_TEMPLATE_PO_QUANTITY_ALLOCATION_SO = 'PO_Quantity_Allocation_SO';
    public static string EMAIL_TEMPLATE_STOCK_QUANTITY_ALLOCATION_SO = 'Stock_Quantity_Allocation_SO';

    public static string EMAIL_TEMPLATE_SUBMIT_CORE_EXCHANGE_FORM = 'Core_Exchange_Form';
    public static string EMAIL_TEMPLATE_FIRST_FOLLOW_UP = 'First_Follow_up';
    public static string EMAIL_TEMPLATE_REQUEST_MORE_INFORMATION = 'Request_More_Information';
    public static string EMAIL_TEMPLATE_DUE_DATE_5 = 'Due_date_5';
    public static string EMAIL_TEMPLATE_DUE_DATE_3 = 'Due_date_3';
    public static string EMAIL_TEMPLATE_DUE_DATE_2 = 'Due_date_2';
    public static string EMAIL_TEMPLATE_DUE_DATE_1 = 'Due_Date_1';
    public static string EMAIL_TEMPLATE_DUE_DATE_DAY = 'D_Day';
    public static string EMAIL_TEMPLATE_DUE_DATE_LATE_SCENARIO = 'Due_Date_Late_Scenario';

    
    //Allocation-Types
    public static string ALLOCATION_TYPE_STOCK = 'Stock';
    public static string ALLOCATION_TYPE_PO = 'Purchase Order';

    //Schedule Names
    public static string SCHEDULER_NAME_ALLOCATION_NOTIFY_CUSTOMER = 'AllocationNotifyCustomer';

    //CronTrigger State
    public static string CRON_TRIGGER_STATE_WAITING = 'WAITING';
    public static string CRON_TRIGGER_STATE_COMPLETE = 'COMPLETE';
    public static string CRON_TRIGGER_STATE_ERROR = 'ERROR';
    public static string CRON_TRIGGER_STATE_EXECUTING = 'EXECUTING';
    
    
    //Customer Exchange Summary Status Values
    public static string CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_SHIPPED = 'Shipped';
    public static string CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_CORE_RECEIVED = 'Core Received';
}